Use StoreOnline

INSERT INTO Usuario(USUARIO,CLAVE,NOMBRE,ESTADO)
VALUES('ADMIN','$2a$10$i0Vvxq8fK0x5rxrtHvq6duO1.9AX6J/O23cM9D09aqKUzzpP1kOO2','ADMINISTRADOR','1');

INSERT INTO Usuario(USUARIO,CLAVE,NOMBRE, ESTADO)
VALUES('DEMO','$2a$10$i0Vvxq8fK0x5rxrtHvq6duO1.9AX6J/O23cM9D09aqKUzzpP1kOO2','DEMO','1');

SELECT * FROM Usuario


INSERT INTO AUTHORITY(NOMBRE,Estado)
VALUES('ROLE_ADMIN','1');  

INSERT INTO AUTHORITY(NOMBRE,Estado)
VALUES('ROLE_USER','1');  

SELECT * FROM Usuario

select * from AUTHORITY

select * from USUARIO_AUTHORITY


INSERT INTO USUARIO_AUTHORITY(USUARIO_ID,AUTHORITY_ID,Estado)
VALUES(0,0,'1');  

INSERT INTO USUARIO_AUTHORITY(USUARIO_ID,AUTHORITY_ID,Estado)
VALUES(0,1,'1');  

INSERT INTO USUARIO_AUTHORITY(USUARIO_ID,AUTHORITY_ID, Estado)
VALUES(1,1,'1');  

select * from USUARIO_AUTHORITY
