server:
  port: 8081

# Oracle #
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=StoreOnline;TrustServerCertificate=True;
    username: sa
    password: 7731
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"