CREATE TABLE USUARIO(
    ID_USUARIO NUMERIC(6,0) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(120) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(120) NOT NULL,
    FECHA_NACIMIENTO VARCHAR2(120) NOT NULL,
    DIRECCION VARCHAR2(120) NOT NULL,
    CODIGO_POSTAL NUMERIC(6,0) NOT NULL,
    TELEFONO VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    USUARIO VARCHAR2(120) NOT NULL,
    CLAVE_ACCESO VARCHAR2(120) NOT NULL,
    ID_ROL NUMERIC(6,0) NOT NULL
);

CREATE SEQUENCE SEQ_USUARIO;

INSERT INTO USUARIO(ID_USUARIO,NOMBRE,APELLIDO_MATERNO,APELLIDO_PATERNO,FECHA_NACIMIENTO,DIRECCION,CODIGO_POSTAL,TELEFONO,EMAIL,USUARIO,CLAVE_ACCESO,ID_ROL)
VALUES(SEQ_USUARIO.NEXTVAL,'Jerry','GARCIA','VERTIZ','01/01/1998','CDMX',1100,'1234567890','GGARCIA@GMAIL.COM','GGARCIA','123456789',1);


INSERT INTO USUARIO(ID_USUARIO,NOMBRE,APELLIDO_MATERNO,APELLIDO_PATERNO,FECHA_NACIMIENTO,DIRECCION,CODIGO_POSTAL,TELEFONO,EMAIL,USUARIO,CLAVE_ACCESO,ID_ROL)
VALUES(SEQ_USUARIO.NEXTVAL,'GERARD','MONTES','VERTIZ','01/01/1997','CDMX',1100,'1234567890','GMONTES@GMAIL.COM','MONTES','123456789',1);


COMMIT;

SELECT * FROM USUARIO;

--drop table USUARIO;