CREATE TABLE CAT_ROLES(
    ID_ROL NUMERIC(6,0) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    DESCRIPCION VARCHAR2(120) NOT NULL,
    ESTATUS NUMERIC(6,0) NOT NULL
);

CREATE SEQUENCE SEQ_CAT_ROLES;