CREATE TABLE USUARIOS(
    ID_USUARIO NUMERIC(6,0) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(120) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(120) NOT NULL,
    FECHA_NACIMIENTO VARCHAR2(120) NOT NULL,
    DIRECCION VARCHAR2(120) NOT NULL,
    CODIGO_POSTAL NUMERIC(6,0) NOT NULL,
    TELEFONO VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    USUARIO VARCHAR2(120) NOT NULL,
    ID_ROL NUMERIC(6,0) REFERENCES CAT_ROLES(ID_ROL)
);

CREATE SEQUENCE SEQ_USUARIOS;