CREATE TABLE CAT_TIPO_TRANSACCION(
    ID_TIPO_TRANSACCION NUMERIC(6,0) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    REFERENCIA VARCHAR2(120) NOT NULL,
    DESCRIPCION VARCHAR2(120) NOT NULL,
    ESTATUS NUMERIC(6,0) NOT NULL
);

CREATE SEQUENCE SEQ_CAT_TIPO_TRANSACCION;


