#server:
#  port: 8081

# Oracle #
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: msmicroservicios
#    password: admin1234
spring:
  application:
    name: ms-ventas-gestion-clientes
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000