CREATE TABLE `cliente` (
  `ID_CLIENTE` int NOT NULL AUTO_INCREMENT,
  `RAZON_SOCIAL` varchar(260) NOT NULL,
  `RFC` char(16) NOT NULL,
  `DIRECCION` varchar(400) NOT NULL,
  `TELEFONO` varchar(20) DEFAULT NULL,
  `CORREO` varchar(60) DEFAULT NULL,
  `ESTADO` char(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_CLIENTE`),
  UNIQUE KEY `RAZON_SOCIAL` (`RAZON_SOCIAL`),
  UNIQUE KEY `RUC` (`RUC`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO CLIENTE ( `RAZON_SOCIAL`, `RFC`, `DIRECCION`, `TELEFONO`, `CORREO`, `ESTADO`) VALUES ( 'MORAL', '1234567890', 'MEX', '1234567890', 'C@C.com', '3');
INSERT INTO CLIENTE ( `RAZON_SOCIAL`, `RFC`, `DIRECCION`, `TELEFONO`, `CORREO`, `ESTADO`) VALUES ( 'FISICA', '1234567890', 'SL', '1234567890', 'B@B.com', '4');

COMMIT;