server:
  port: 8099

# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: msmicroservicios
    password: admin1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"