server:
  port: 8082

# Oracle #
spring:
  datasource:
    url: jdbc:mysql://localhost/ms-rest?serverTimezone=GMT-6
    username: ms_cliente
    password: ms_cliente
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
