USE StoreOnline
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AUTHORITY](
	[AUTHORITY_ID]  [int] IDENTITY(0,1) NOT NULL,
	NOMBRE [nvarchar](120) NOT NULL,
	ESTADO [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AUTHORITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



    