USE StoreOnline
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIO_AUTHORITY ](
	[USUARIO_AUTHORITY_ID]  [int] IDENTITY(0,1) NOT NULL,
	Usuario_Id int NOT NULL,
	AUTHORITY_ID int NOT NULL,
	ESTADO VARCHAR(100)
PRIMARY KEY CLUSTERED 
(
	[USUARIO_AUTHORITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



    