CREATE TABLE CAT_PAQUETERIAS(
    ID_PAQUETERIA NUMERIC(6,0) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    DIRECCION VARCHAR2(120) NOT NULL,
    CODIGO_POSTAL NUMERIC(9,0) NOT NULL,
    HORARIO VARCHAR2(120) NOT NULL,
    ESTATUS NUMERIC(9,0) NOT NULL
);

CREATE SEQUENCE SEQ_CAT_PAQUETERIAS;