CREATE TABLE CAT_PROVEEDORES(
    ID_PROVEEDOR NUMERIC(6,0) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    DIRECCION VARCHAR2(120) NOT NULL,
    RFC VARCHAR2(120) NOT NULL,
    ESTATUS NUMERIC(6,0) NOT NULL,
    ID_CATEGORIA NUMERIC(6,0) REFERENCES CAT_CATEGORIAS(ID_CATEGORIA)
);

CREATE SEQUENCE SEQ_CAT_PROVEEDORES;