CREATE TABLE DIRECCION_ENTREGA(
    ID_DIRECCION NUMERIC(6,0) NOT NULL PRIMARY KEY,
    ID_USUARIO NUMERIC(6,0) REFERENCES USUARIOS(ID_USUARIO),
    CODIGO_POSTAL NUMERIC(6,0) NOT NULL,
    DIRECCION VARCHAR2(120) NOT NULL,
    REFERENCIAS VARCHAR2(120) NOT NULL,
    GEOLOCALIZACION VARCHAR2(120) NOT NULL,
    ESTATUS NUMERIC(6,0) NOT NULL
);

CREATE SEQUENCE SEQ_DIRECCION_ENTREGA;


