CREATE TABLE RECURSO_PAGOS(
    ID_RECURSO NUMERIC(6,0) NOT NULL PRIMARY KEY,
    ID_USUARIO NUMERIC(6,0) REFERENCES USUARIOS(ID_USUARIO),
    NUMERO_TARJETA VARCHAR2(120) NOT NULL,
    FECHA_TARJETA VARCHAR2(120) NOT NULL,
    NOMBRE_TARJETA VARCHAR2(120) NOT NULL,
    BANCO_TARJETA VARCHAR2(120) NOT NULL,
    ESTATUS NUMERIC(6,0) NOT NULL
);

CREATE SEQUENCE SEQ_RECURSO_PAGOS;


